#PROJECT NAME
PROJECT_NAME = 'Pekanu-User'

#SECRET KEY FOR AUTHENTICATION
AUTH_SECRET_KEY = "vn9RMTIxXrPOBwTIkGk3SQN5vc"

#TELEGRAM CREDENTIALS
TELEGRAM_API_TOKEN = 'ADD TELEGRAM BOT API TOKEN'
TELEGRAM_API_URL = 'https://api.telegram.org/bot'
TELEGRAM_BASE_URL = 'https://telegram.me/'
TELEGRAM_CHAT_ID = ['ADD TELEGRAM USERID']

#MONGODB CREDENTIALS
MONGODB_URL = 'ADD MONGODB URL'
DATABASE_NAME = 'ADD MONGODB DATABASE NAME'
